include(CMakeFindDependencyMacro)
find_dependency(vart COMPONENTS runner util dpu-controller REQUIRED)
find_dependency(Protobuf 3.4.0 REQUIRED)
include("${CMAKE_CURRENT_LIST_DIR}/math-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/model_config-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/xnnpp-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/dpu_task-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/classification-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/facedetect-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/lanedetect-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/multitask-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/openpose-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/posedetect-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/refinedet-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/reid-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/segmentation-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ssd-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/tfssd-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/yolov2-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/yolov3-targets.cmake")
